 Vae model:  camcan_400_Aug_2_100  NN model:  app4_2_100
Using device: cuda:0
Loading train set for subj
Best Threshold=0.273513, G-Mean=0.709
AUC training :  0.6108374384236452
0.2735131924802707
0.0
Loading test set for subj
Subject  Brats17_CBICA_AMH_1_t2_unbiased.nii.gz  Number of Slices:  140
Traceback (most recent call last):
  File "restore_MAP_NN.py", line 112, in <module>
    for batch_idx, (scan, seg, mask) in enumerate(subj_loader):
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/datasets.py", line 325, in __getitem__
    img_trans, seg_trans, mask_trans = self.transform(img_data, seg_data)
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/datasets.py", line 308, in transform
    mask_PIL = Image.fromarray(mask * 255)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/PIL/Image.py", line 2670, in fromarray
    arr = obj.__array_interface__
AttributeError: 'Tensor' object has no attribute '__array_interface__'

