Name:  app5_2_1_ Lr_rate:  0.0001 Use Teacher:  False  Riter:  20  Subjs:  2
Using device: cuda:0
['Brats17_CBICA_BFB_1_t2_unbiased.nii.gz']
validation subject ['Brats17_CBICA_BHK_1_t2_unbiased.nii.gz']
Loading train set for subj
Subject  Brats17_CBICA_BFB_1_t2_unbiased.nii.gz  Number of Slices:  143
/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3257: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
AUC :  0.7249392128482409
Loss :  nan
Loading train set for subj
Subject  Brats17_CBICA_BHK_1_t2_unbiased.nii.gz  Number of Slices:  146
Traceback (most recent call last):
  File "train_restore_MAP_NN.py", line 211, in <module>
    train=False, log=bool(batch_idx % 3))
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/restoration.py", line 120, in train_run_map_NN
    __, z_mean, z_cov, __ = vae_model(img_ano.unsqueeze(1).double())
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/models/vae.py", line 55, in forward
    return self.decode(z), mu, logvar, res
  File "/scratch_net/biwidl214/jonatank/code_home/restor_MAP/models/vae.py", line 40, in decode
    z = self.decoder(z)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 559, in forward
    return F.leaky_relu(input, self.negative_slope, self.inplace)
  File "/scratch_net/biwidl214/jonatank/anaconda3/envs/JKMT/lib/python3.7/site-packages/torch/nn/functional.py", line 1063, in leaky_relu
    result = torch._C._nn.leaky_relu(input, negative_slope)
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 10.92 GiB total capacity; 10.28 GiB already allocated; 81.56 MiB free; 10.32 GiB reserved in total by PyTorch)
